# Generated by Django 5.1.1 on 2024-09-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0005_service_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
